create database RetailsalesAnalytics;
USE RetailSalesAnalytics;
select * from brands;
select * from categories;
select * from customers;
select * from products;
select * from stores;
select * from staffs;
select * from orders;
select * from order_items;
select count(*) from stocks;

-- =============================================================================
-- TASK 3: Inner Join for Order Details
--  Join orders, order_items, and products to display detailed line items.

select o.order_id,o.order_date,o.customer_id,p.product_name,oi.total_price,oi.quantity
from orders as o
inner join order_items as oi
on oi.order_id=o.order_id
inner join products as p
on oi.product_id=p.product_id;

-- ==================================================================================
-- TASK 4: Total Sales by Store
-- Write a query to group sales (total_price) by each store_id.

select s.store_id,s.store_name,sum(oi.total_price) as total_sales
from orders as o
inner join order_items as oi
on o.order_id=oi.order_id
inner join stores as s
on o.store_id=s.store_id
group by store_id,store_name;

-- ================================================================================
-- Top 5 Selling Products
-- Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.

select product_name,sum(quantity) as quantity_sold, sum(total_price) as total_sales from order_items
group by product_name
order by quantity_sold desc limit 5;

-- ====================================================================================
-- TASK 6 Customer Purchase Summary
-- For each customer, return total orders placed, total items purchased, and total revenue.

select c.customer_id,c.first_name,count(o.order_id) as order_count, sum(oi.total_price) as total_revenue from customers as c
inner join orders as o
on c.customer_id=o.customer_id
inner join order_items as oi
on o.order_id=oi.order_id
group by customer_id, first_name
order by order_count desc;

-- =====================================================================================
-- 7 Segment Customers by Total Spend
-- Write a query to classify customers into spending brackets (e.g., low, medium, high).
select customer_id,first_name,total_revenue,
 case
when total_revenue>15000 then "High value customer"
when total_revenue between 5000 and 15000 then "Medium value customer"
when total_revenue<5000 then "Low value customer"
end as cutomer_segment
from (select c.customer_id,c.first_name,count(o.order_id) as order_count, sum(oi.total_price) as total_revenue from customers as c
inner join orders as o
on c.customer_id=o.customer_id
inner join order_items as oi
on o.order_id=oi.order_id
group by customer_id, first_name
order by order_count desc) as customer_summary;

-- ========================================================================================================================================
-- 8 Staff Performance Analysis
-- Analyze total revenue generated by each staff member based on their handled orders.

select s.staff_id,s.first_name,count(o.order_id) as total_orders, sum(oi.total_price) as total_revenue from staffs as s
inner join orders as o
on s.staff_id=o.staff_id
inner join order_items as oi
on o.order_id=oi.order_id
group by s.staff_id,s.first_name;

-- ==============================================================================================================
-- TASK 9 Stock Alert Query
-- Write a query to list products where stock quantity < 10 in any store.

select p.product_id,p.product_name,s.quantity,
case
when s.quantity <= 10 then 'Low Stock'
when s.quantity between 11 and 50 then 'Medium Stock'
else 'High Stock'
end as stock_status
from stocks as s
inner join products as p
on s.product_id = p.product_id;

-- ====================================================================
-- TASK 10 Create Final Segmentation Table
-- Create a table customer_segments that will be populated from Python ML results later.

SELECT * FROM customer_segments;